# Based on the default Ruby config.yml.
# https://circleci.com/docs/2.0/language-ruby/

version: 2
jobs:
  build:
    docker:
       - image: circleci/ruby:2.5.1
      
    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - bundle-{{ checksum "Gemfile.lock" }}
          - bundle-

      - run: bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: bundle-{{ checksum "Gemfile.lock" }}
        
      - run:
          name: run tests
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)"
            
            bundle exec rspec \
              --format progress \
              --format RspecJunitFormatter \
              --out /tmp/test-results/rspec.xml \
              --format progress \
              $TEST_FILES

      # https://circleci.com/docs/2.0/configuration-reference/#store_test_results 
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
